use std::fs;

use rotiv_core::find_project_root;

use crate::commands::spec_sync::{
    discover_routes_for_project, discover_models_entries_pub, read_project_name,
};
use crate::error::CliError;
use crate::output::{OutputMode, human};

pub fn run(mode: OutputMode) -> Result<(), CliError> {
    let project_dir = find_project_root().map_err(CliError::Rotiv)?;

    let project_name = read_project_name(&project_dir);
    let routes = discover_routes_for_project(&project_dir);
    let models = discover_models_entries_pub(&project_dir);
    let timestamp = current_timestamp();

    let mut md = String::new();

    md.push_str(&format!("# Project Context — {}\n\n", project_name));
    md.push_str("> Auto-generated by `rotiv context regen`. Do not edit manually.\n");
    md.push_str(&format!("> Last updated: {}\n\n", timestamp));

    // Routes table
    md.push_str("## Routes\n\n");
    md.push_str("| Path | File | Loader | Action | Component |\n");
    md.push_str("|------|------|--------|--------|-----------|\n");
    for route in &routes {
        let path = route["path"].as_str().unwrap_or("");
        let file = route["file"].as_str().unwrap_or("");
        let loader = if route["has_loader"].as_bool().unwrap_or(false) { "✓" } else { "✗" };
        let action = if route["has_action"].as_bool().unwrap_or(false) { "✓" } else { "✗" };
        let component = if route["has_component"].as_bool().unwrap_or(false) { "✓" } else { "✗" };
        md.push_str(&format!(
            "| `{}` | `{}` | {} | {} | {} |\n",
            path, file, loader, action, component
        ));
    }
    if routes.is_empty() {
        md.push_str("| (no routes found) | | | | |\n");
    }
    md.push('\n');

    // Models table
    md.push_str("## Models\n\n");
    md.push_str("| Name | Table | File |\n");
    md.push_str("|------|-------|------|\n");
    for model in &models {
        let name = model["name"].as_str().unwrap_or("");
        let table = model["table"].as_str().unwrap_or("");
        let file = model["file"].as_str().unwrap_or("");
        md.push_str(&format!("| {} | {} | `{}` |\n", name, table, file));
    }
    if models.is_empty() {
        md.push_str("| (no models found) | | |\n");
    }
    md.push('\n');

    // Conventions
    md.push_str("## Conventions\n\n");
    md.push_str("- Routes directory: `app/routes`\n");
    md.push_str("- Models directory: `app/models`\n");
    md.push_str("- Output directory: `dist`\n");
    md.push_str("- Database: SQLite (dev) at `app/.rotiv/dev.db`\n\n");

    // Quick reference
    md.push_str("## Quick Reference\n\n");
    md.push_str("- Add a route: `rotiv add route <path>`\n");
    md.push_str("- Add a model: `rotiv add model <Name>`\n");
    md.push_str("- Run migrations: `rotiv migrate`\n");
    md.push_str("- Validate project: `rotiv validate`\n");
    md.push_str("- Sync spec: `rotiv spec sync`\n");

    // Write to .rotiv/context.md
    let context_path = project_dir.join(".rotiv").join("context.md");
    if let Some(parent) = context_path.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(&context_path, &md)?;

    match mode {
        OutputMode::Human => {
            human::print_success(&format!(
                ".rotiv/context.md updated ({} routes, {} models)",
                routes.len(),
                models.len()
            ));
        }
        OutputMode::Json => {
            println!(
                "{}",
                serde_json::json!({
                    "ok": true,
                    "file": ".rotiv/context.md",
                    "routes": routes.len(),
                    "models": models.len(),
                })
            );
        }
    }

    Ok(())
}

fn current_timestamp() -> String {
    use std::time::{SystemTime, UNIX_EPOCH};
    let secs = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_secs();
    let secs_per_day = 86400u64;
    let days = secs / secs_per_day;
    let time = secs % secs_per_day;
    let hh = time / 3600;
    let mm = (time % 3600) / 60;
    let ss = time % 60;
    let (year, month, day) = days_to_ymd(days);
    format!("{:04}-{:02}-{:02}T{:02}:{:02}:{:02}Z", year, month, day, hh, mm, ss)
}

fn days_to_ymd(days: u64) -> (u64, u64, u64) {
    let z = days + 719468;
    let era = z / 146097;
    let doe = z - era * 146097;
    let yoe = (doe - doe / 1460 + doe / 36524 - doe / 146096) / 365;
    let y = yoe + era * 400;
    let doy = doe - (365 * yoe + yoe / 4 - yoe / 100);
    let mp = (5 * doy + 2) / 153;
    let d = doy - (153 * mp + 2) / 5 + 1;
    let m = if mp < 10 { mp + 3 } else { mp - 9 };
    let y = if m <= 2 { y + 1 } else { y };
    (y, m, d)
}
